source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CTEventCalendar_Example', :exclusive => true do
  pod "CTEventCalendar", :path => "../"
end

target 'CTEventCalendar_Tests', :exclusive => true do
  pod "CTEventCalendar", :path => "../"

  
end
