language: objective-c
osx_image: xcode7
env:
  - DESTINATION="OS=9.0,name=iPhone 6" SCHEME="Eureka" SDK=iphonesimulator9.0
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail && xcodebuild test -workspace Example/CTEventCalendar.xcworkspace -scheme CTEventCalendar-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
